version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    command: /start
    volumes:
      - .:/app
    ports:
      - 8010:8000
    env_file:
      - .env.dev
    depends_on:
      - redis
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}

  redis:
    image: redis:6-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - .env.dev
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db

volumes:
  postgres_data: