# Generated by Django 4.0.6 on 2022-07-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False, help_text='Whether the record is deleted or not (soft-delete)')),
                ('coin_id', models.CharField(max_length=255)),
                ('trigger_value', models.DecimalField(decimal_places=3, help_text='When the coin value crosses the specified `trigger_value` the alert is triggered.', max_digits=16)),
                ('triggered_on', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
