# Generated by Django 4.0.6 on 2022-07-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='trigger_on_lte',
            field=models.BooleanField(default=True, help_text='Whether to trigger the alert when the price reaches or falls below the set value. Otherwise when the price reaches or rises above the set value.'),
            preserve_default=False,
        ),
    ]
