# Generated by Django 4.0.6 on 2022-07-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alert_trigger_on_lte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='trigger_on_lte',
            field=models.BooleanField(editable=False, help_text='Whether to trigger the alert when the price reaches or falls below the set value. Otherwise when the price reaches or rises above the set value.'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='trigger_value',
            field=models.DecimalField(decimal_places=3, help_text='When the coin value crosses the specified `trigger_value` in USD, the alert is triggered.', max_digits=16),
        ),
    ]
